@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "62e539c0d8b514f6e42e3b5b",
  "postId": "62ed227827461b3ece2d6f25",
  "type": "love",
  "previousReaction": "",
  "postReactions": {"like": 0,"love": 0,"happy": 0,"sad": 1,"wow": 0,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/dyamr9ym3/image/upload/v1659189696/62e539c0d8b514f6e42e3b5b"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/62ea82366d7191261d4ff0de/sad/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/62ea82366d7191261d4ff0de
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Manny/62ea82366d7191261d4ff0de
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Danny
Content-Type: application/json
Accept: application/json
withCredentials: true
